### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 254Sidney** [lev1khachatryan/Video_Background_Editor#1]
am getting the following when i run as per instructions,i seem not to figure out how to solve the error:

PS C:\Users\ADMIN\Desktop\backgroundprj\Video_Background_Editor> cd python
PS C:\Users\ADMIN\Desktop\backgroundprj\Video_Background_Editor\python> python bg_fg_combiner.py
[ WARN:0] global C:\projects\opencv-python\opencv\modules\core\src\utils\samples.cpp (59) cv::samples::findFile cv::samples::findFile('C:/ADMIN/Desktop/backgroundprj/VideoBackgroundEditor/_input/background.avi') => ''
[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): C:/ADMIN/Desktop/backgroundprj/VideoBackgroundEditor/_input/background.avi in function 'cv::icvExtractPattern'

Traceback (most recent call last):
  File "bg_fg_combiner.py", line 143, in <module>
    main()
  File "bg_fg_combiner.py", line 135, in main
    background = bgSubtractor(INPUT_PATH + BG_VIDEO_NAME)    
  File "bg_fg_combiner.py", line 42, in bgSubtractor
    median_frame = np.median(frames, axis=0)
  File "<__array_function__ internals>", line 5, in median   
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\lib\function_base.py", line 3501, in median
    r, k = _ureduce(a, func=_median, axis=axis, out=out,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\lib\function_base.py", line 3410, in _ureduce
    r = func(a, **kwargs)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\lib\function_base.py", line 3535, in _median
    part = partition(a, kth, axis=axis)
  File "<__array_function__ internals>", line 5, in partition
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\core\fromnumeric.py", line 745, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)      
TypeError: '<' not supported between instances of 'NoneType' 
and 'NoneType'
PS C:\Users\ADMIN\Desktop\backgroundprj\Video_Background_Editor\python>

**Comment by HaithemH** [comment]
Hi there,
TypeError: '<' not supported between instances of 'NoneType' error means that your input video did not upload/been read successfully. Check you video inputs and try to use .avi video format.
